### ISSUE TITLE
[Refactor] Game Event API

### ISSUE THREAD

**Issue by milkory** [APJifengc/Bingo#15]
Currently, we are using a very procedure-oriented way to implement game process controlling (because of some historical issues). It can be turned into a Game Event API which has more extensibility.

See [`BingoGame.java`](https://github.com/APJifengc/Bingo/blob/4ad354592cb0a5a7c6fe422866a76c92ef7d4a14/src/main/java/io/apjifengc/bingo/api/game/BingoGame.java).

**Comment by APJifengc** [comment]
Changed it into Bingo Timer API.

Code has been done, waiting for testing.

**Comment by APJifengc** [comment]
Testing and bug fixing are done.
