### ISSUE TITLE
[Bug] Number of players displayed incorrectly

### ISSUE THREAD

**Issue by LoliColleen** [APJifengc/Bingo#18]
![XF1(SS) GE8U{43}5O01(HN](https://user-images.githubusercontent.com/76620594/152982822-260adff5-6df4-4a49-a4dd-e240a96e6567.png)
![7PJDKYP 2O38N7MJWS9RO H](https://user-images.githubusercontent.com/76620594/152982845-883e501c-0021-4093-a8d4-5d14f95482c6.png)

**Comment by milkory** [comment]
Detailed process of reproducing is required.

**Comment by APJifengc** [comment]
Can you provide more information?
If the error is occurred after the game restarted (with bungee supports on), it is probably a error caused by #19 .
If it's not, please describe how it happens.
