### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by devliegerwout** [APJifengc/Bingo#21]
https://i.imgur.com/Ahv9HG3.png
https://pastebin.com/BQnisD7h

The game is not auto starting, when the min players is reached. 

Can you help me? Thanks a lot!

**Comment by APJifengc** [comment]
Umm... I think you posted in the wrong repository. The config file isn't ours.
I'm at school currently, so I can only check Pastebin.
And since you came here, consider trying our Bingo plugin! We have other kinds of tasks besides collecting items, like killing mobs, making the game more wonderful.
