### ISSUE TITLE
Stays in spectator mode when game ends

### ISSUE THREAD

**Issue by Oddengineers** [APJifengc/Bingo#25]
After game has ended if you are the winner and do /bingo leave it will teleport you back to where you were however you are still in spectator mode and have to do the gamemode command to go back to survival mode. If you let the game end on its own you are teleported back to overworld spawn and in survival mode but not the spawnpoint that was set by player and not where you were when you joined the bingo game such as your base or where ever else. Is there anyway to fix these issues?

**Comment by APJifengc** [comment]
Fixed. However, I'm at school so that I can't test it and I don't have time to release a new version. You can download the latest build in GitHub Action.
