### ISSUE TITLE
Inventory lost

### ISSUE THREAD

**Issue by Leahcimkrob** [APJifengc/Bingo#26]
When I start a game, the items are taken away. Once the game is over, these are not returned, so the entire inventory is lost.
Paper 1.19.3

**Comment by APJifengc** [comment]
Sorry for making trouble. The plugin is designed for using in a separate server, as we mentioned in the spigot page and the bukkit page.

It was designed that you can make a small lobby if you are simply playing with friends, and you can enable the Bungeecord support to make it work in large servers. We do not recommend installing the plugin in an existing server. Sorry again.

**Comment by APJifengc** [comment]
Probably won't fix this, but if I got time, there stands a chance.

The project is almost abandoned, so yeah. 

Also duplicated to #22.
