### ISSUE TITLE
cannot start game with 1 player even if I set the min players to 1 in the config.yml

### ISSUE THREAD

**Issue by ski-freak** [APJifengc/Bingo#27]
Looking into playing this plugin with some friends, wanted to check it out and test it on my own first. However, as the title says, I can't seem to do this. Also I see no way to just force start the bingo game from the floating thingy while it says waiting for more people. I also tried reducing the max players to 1 and had the same issue.

**Comment by APJifengc** [comment]
Have you tried changing the `start-time` config?

**Comment by milkory** [comment]
no further information
