### ISSUE TITLE
Player not teleported back to bingo world after death

### ISSUE THREAD

**Issue by ten0rplaya04** [APJifengc/Bingo#5]
Issue: Players respawn in "world" instead of "bingo"

Description: Players who die during a bingo game are sent back to the original "world" instead of being sent to the spawn of "bingo".  They are still part of the bingo game and are able to play from "world." After someone finishes the game, any players who have not been moved back to "bingo" end up in Spectator mode on "world" instead of the gamemode of "world". 

Recreate:
- Start and Join a bingo game
- Die
- Respawn into "world"

Environment:
Minecraft 1.15.2
Bingo 1.0.0-beta.1
Multiverse-Core 4.1.0-b775

Other comment: Thank you for putting your time and effort into this plugin.  It is much appreciated and my play group has been enjoying our time with it.

**Comment by milkory** [comment]
Thank you for your report and we are sorry about our long non-response.

The bug is fixed in [v1.0.0-beta.2](https://github.com/APJifengc/Bingo/releases/tag/v1.0.0-beta.2). The new version also added entity tasks. You can try them out.
