### ISSUE TITLE
[Feature Request] Start game with items

### ISSUE THREAD

**Issue by ten0rplaya04** [APJifengc/Bingo#8]
Good day.

I would like to see an option with config to give items to players to start the game. After a few games in a row, making tools and food becomes tiresome and takes away from the game of actually finding the bingo items. For my playgroup, I've taken to starting the game and immediately utilizing the give command to provide food and basic tools and I believe having this option as a standard part of the plugin would benefit the community.

Thank you for reviewing this request.

**Comment by APJifengc** [comment]
Thanks for requesting! Unfortuntely now I have much schoolwork and I almost have no time to update this project :< 
(probably will update in january or february or maybe @Yoooooory will update this project)

**Comment by milkory** [comment]
We are now reloading this plugin. This request will be taken into account after we finished it.

**Comment by APJifengc** [comment]
added.
